DROP TABLE if exists APPRENTI;

DROP TABLE if exists STAGIAIRE;

DROP TABLE if exists ENTREPRISE;

DROP TABLE if exists ETUDIANT;

DROP TABLE if exists GROUPEINFO1;

DROP TABLE if exists ENSEIGNANT;

CREATE TABLE ENSEIGNANT(
    IDENS int(3),
    NOMENS VARCHAR(30),
    PRENOMENS VARCHAR(30),
    
    CONSTRAINT PK_IDENS PRIMARY KEY(IDENS),
	);

CREATE TABLE GROUPEINFO1(
    IDGROUPE1 VARCHAR(1),
    TUTEURGROUPE VARCHAR(3),
    
    CONSTRAINT FK_IDENS2_ENSEIGNANT foreign key ENSEIGNANT(IDENS) REFERENCES ENSEIGNANT(IDENS),
    CONSTRAINT PK_IDGROUPE1 PRIMARY KEY(IDGROUPE1),
);

CREATE TABLE ETUDIANT(
    IDETUD INT,
    NOMETUD VARCHAR(30),
    PRENOMETUD VARCHAR(20),
    SEXE VARCHAR(1),
    BAC VARCHAR(50),
    NOMLYCEE VARCHAR(50),
    DEPLYCEE INT(2),
    LEGROUPEINFO1 VARCHAR(1),
    PARCOURSINFO2 VARCHAR(2),
    FORMATIONINFO2 VARCHAR(3),
    POURSUITEETUDES VARCHAR(50),
    
    CONSTRAINT FK_IDGROUPE1_GROUPEINFO foreign key GROPUEINFO1(iDGROUPE1) REFERENCES GROUPEINFO1(IDGROUPE1),
    CONSTRAINT PK_IDETUD_ETUDIANT PRIMARY KEY(IDETUD),
);

CREATE TABLE ENTREPRISE(
    IDENTREPRISE int(2),
    NOMENTREPRISE VARCHAR(50),
    DEPENTREPRISE int(2),
    
    CONSTRAINT PK_IDENTREPRISE_ENTREPRISE PRIMARY KEY(IDENTREPRISE),
	);

CREATE TABLE STAGIAIRE(
    ETUDSTAGIAIRE INT,
    ENTREPRISESTAGE INT(2),
    
	CONSTRAINT FK_IDETUD_ETUDIANT foreign key STAGIARE(ETUDSTAGIAIRE) REFERENCES ETUDIANT(IDETUD),
	CONSTRAINT FK_IDENTREPRISE_ENTREPRISE foreign key STAGIAIRE(ENTREPRISESTAGE) REFERENCES ENTREPRISE(IDENTREPRISE),
);

CREATE TABLE APPRENTI(
    ETUDAPP int,
    ENTREPRISEAPP int(2),
    TUTEURAPP VARCHAR(3),
    
	CONSTRAINT FK_IDETUD_ETUDIANT foreign key APPRENDTI(ETUDEAPP) references ETUDIANT(IDETUD),
	CONSTRAINT FK_IDENTREPRISE_ENTREPRISE foreign key APPRENTI(ENTREPRISEAPP) references ENTREPRISE(IDENTREPRISE),
    CONSTRAINT FK_IDENS_ENSEIGNANT foreign key APPRENTI(TUTEURAPP) references ENSEIGNANT(IDENS),
);