CREATE OR REPLACE VIEW vue_Etud_Stag_Ent
AS 
SELECT NOMETUD
FROM ETUDIANT
	JOIN STAGIAiRE ON IDETUD = ETUDSTAGIAIRE
        JOIN ENTREPRISE ON ENTREPRISESTAGE = IDENTREPRISE
;


SELECT *
FROM vue_Etud_Stag_Ent
;

CREATE OR REPLACE VIEW vue_Etud_App_Ent
AS 
SELECT NOMETUD
FROM ETUDIANT
	JOIN APPRENTI ON IDETUD = ETUDAPP
        JOIN ENTREPRISE ON ENTREPRISEAPP = IDENTREPRISE
;


SELECT *
FROM vue_Etud_App_Ent
;