SELECT TO_NUMBER(SOLDE), COUNT(NUMOPERATION) FROM COMPTE LEFT JOIN OPERATION ON NUMCOMPTE = LECOMPTE WHERE NUMCOMPTE = 16 GROUP BY NUMCOMPTE, SOLDE; --100000 | 0    Sucess 
INSERT INTO OPERATION(NUMOPERATION, MONTANT,TYPEOPERATION,LECLIENT,LECOMPTE) VALUES(1001,10000,'RETRAIT',13,16); --OK   Sucess '1 ligne inséré'
INSERT INTO OPERATION(NUMOPERATION, MONTANT,TYPEOPERATION,LECLIENT,LECOMPTE) VALUES(1002,10000,'RETRAIT',13,16); --OK    Sucess '1 ligne inséré'
SELECT TO_NUMBER(SOLDE), COUNT(NUMOPERATION) FROM COMPTE LEFT JOIN OPERATION ON NUMCOMPTE = LECOMPTE WHERE NUMCOMPTE = 16 GROUP BY NUMCOMPTE, SOLDE; --80000 | 2   Sucess COUNT(NUMOPERATION) = 2
INSERT INTO OPERATION(NUMOPERATION, MONTANT,TYPEOPERATION,LECLIENT,LECOMPTE) VALUES(1000,1000000,'DEPOT',13,16); --OK Sucess '1 ligne inséré'
SELECT TO_NUMBER(SOLDE), COUNT(NUMOPERATION) FROM COMPTE LEFT JOIN OPERATION ON NUMCOMPTE = LECOMPTE WHERE NUMCOMPTE = 16 GROUP BY NUMCOMPTE, SOLDE; --1080000 | 3  Sucess COUNT(NUMOPERATION) = 3
INSERT INTO OPERATION(NUMOPERATION, MONTANT,TYPEOPERATION,LECLIENT,LECOMPTE) VALUES(1003,100000,'RETRAIT',13,16); --Pas d'insertion -- Erreur SQL : ORA-20500: Tentative de retrait de 120000 euros sur le compte numéro 16 le 07/01/25
SELECT TO_NUMBER(SOLDE), COUNT(NUMOPERATION) FROM COMPTE LEFT JOIN OPERATION ON NUMCOMPTE = LECOMPTE WHERE NUMCOMPTE = 16 GROUP BY NUMCOMPTE, SOLDE; --1080000 | 3 Sucess
UPDATE OPERATION SET TYPEOPERATION = 'RETRAIT' WHERE LECOMPTE=16; -- Pas de modification -- Erreur SQL : ORA-20500: Tentative de retrait de 1020000 euros sur le compte numéro 16 le 07/01/25
UPDATE OPERATION SET MONTANT = 10000 WHERE NUMOPERATION=1000; --OK Sucess 
UPDATE OPERATION SET TYPEOPERATION = 'RETRAIT' WHERE LECOMPTE=16; -- OK Sucess
SELECT TO_NUMBER(SOLDE), COUNT(NUMOPERATION) FROM COMPTE LEFT JOIN OPERATION ON NUMCOMPTE = LECOMPTE WHERE NUMCOMPTE = 16 GROUP BY NUMCOMPTE, SOLDE; --1060000 | 3    Sucess
INSERT INTO OPERATION(NUMOPERATION, MONTANT,TYPEOPERATION,LECLIENT,LECOMPTE) VALUES(1004,1000,'RETRAIT',13,16); --Pas d'insertion -- Erreur SQL : ORA-20600: Tentative de plus de trois retraits sur le compte numéro 16 le 07/01/25
INSERT INTO OPERATION(NUMOPERATION, MONTANT,TYPEOPERATION,LECLIENT,LECOMPTE) VALUES(1004,1000,'DEPOT',13,16); --OK   Sucess
SELECT TO_NUMBER(SOLDE), COUNT(NUMOPERATION) FROM COMPTE LEFT JOIN OPERATION ON NUMCOMPTE = LECOMPTE WHERE NUMCOMPTE = 16 GROUP BY NUMCOMPTE, SOLDE; --1061000 | 4   Sucess
UPDATE OPERATION SET TYPEOPERATION = 'RETRAIT' WHERE NUMOPERATION=1004; -- Pas de modification -- Erreur SQL : ORA-20600: Tentative de plus de trois retraits sur le compte numéro 16 le 07/01/25     Sucess   
UPDATE OPERATION SET TYPEOPERATION = 'DEPOT' WHERE TYPEOPERATION = 'RETRAIT'; -- OK Sucess
UPDATE OPERATION SET TYPEOPERATION = 'RETRAIT' WHERE NUMOPERATION=1004; -- OK Sucess
SELECT TO_NUMBER(SOLDE), COUNT(NUMOPERATION) FROM COMPTE LEFT JOIN OPERATION ON NUMCOMPTE = LECOMPTE WHERE NUMCOMPTE = 16 GROUP BY NUMCOMPTE, SOLDE; --1119000 | 4    Sucess
ROLLBACK;
--DROP TRIGGER DIVERS_C_TRIGGER;